### ISSUE TITLE
UnityAgentsException: Variable Length Observations are not supported by the trainer

### ISSUE THREAD

**Issue by PenguineZhang** [niwcpac-nautica/nautica-challenge-public#1]
I am using Unity 2020.3.12f1 on Ubuntu 18.04 and ML Agent 2.0.0-pre.3. When I tried to run mlagent-learn command then click the play button on Unity, the following error popped up. Any idea?

![Screenshot from 2021-07-18 21-17-04](https://user-images.githubusercontent.com/17698544/126102193-ed6d3197-4fb4-4a06-84ed-94f0d7a4044c.png)

**Comment by zako42** [comment]
Not too sure about this - I've only used the environment in Windows.  Will check with the others to see if anyone has tested in Linux (some of them have tested on Mac, but not sure about Linux).  If not, we can try installing VirtualBox and Ubuntu 18.04 to see if we run into the same thing.

Also, you can try checking the ML Agents repo to see if they have anything about the problem too:  https://github.com/Unity-Technologies/ml-agents

**Comment by PenguineZhang** [comment]
@zako42 I think the issue was that I used outdated mlagents in python. I tried on a new machine and it works out of the box.
